#!/usr/bin/env bash

jspm config registries.github.remote https://github.jspm.io
jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
jspm config registries.github.maxRepoSize 0
jspm config registries.github.handler jspm-github

jspm install -y

# FIXME delete conf.js with credentials

# necessary here? or maybe before jspm?
npm install
